/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MaterHospitalGUI.java
 *
  */

package SeratonHotel;
/**
 *
 * @author cmuntean
 */

public class MaterHospitalGUI extends javax.swing.JFrame {

    /** Creates new form MaterHospitalGUI */
    private PQInterface myPQueue;
    public MaterHospitalGUI() {
        myPQueue = new HotelPriorityQueue();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeJLabel = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        symptomJLabel = new javax.swing.JLabel();
        nameJText = new javax.swing.JTextField();
        symptomJText = new javax.swing.JTextField();
        numPatientsJButton = new javax.swing.JButton();
        addJButton = new javax.swing.JButton();
        removeJButton = new javax.swing.JButton();
        displayJLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDisplay = new javax.swing.JTextArea();
        symptomJLabel1 = new javax.swing.JLabel();
        priorityJText = new javax.swing.JTextField();
        listJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        welcomeJLabel.setForeground(java.awt.Color.blue);
        welcomeJLabel.setText("Welcome to A&E Mater Hospital");

        nameJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameJLabel.setForeground(java.awt.Color.red);
        nameJLabel.setText("Please enter your name");

        symptomJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        symptomJLabel.setForeground(java.awt.Color.red);
        symptomJLabel.setText("Priority");

        nameJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTextActionPerformed(evt);
            }
        });

        numPatientsJButton.setText("No. Customers in Q");
        numPatientsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPatientsJButtonActionPerformed(evt);
            }
        });

        addJButton.setText("Add Patient");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        removeJButton.setText("Remove Patient");
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });

        displayJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextAreaDisplay.setColumns(20);
        jTextAreaDisplay.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDisplay);

        symptomJLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        symptomJLabel1.setForeground(java.awt.Color.red);
        symptomJLabel1.setText("Please enter your main symptom");

        priorityJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priorityJTextActionPerformed(evt);
            }
        });

        listJButton.setText("List Patients");
        listJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcomeJLabel)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(listJButton)
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(displayJLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numPatientsJButton)
                                .addGap(26, 26, 26)
                                .addComponent(addJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(removeJButton)
                                .addGap(20, 20, 20))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(symptomJLabel)
                        .addGap(174, 174, 174)
                        .addComponent(priorityJText))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameJLabel)
                        .addGap(75, 75, 75)
                        .addComponent(nameJText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(symptomJLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(symptomJText)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeJLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameJLabel)
                    .addComponent(nameJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(symptomJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(symptomJLabel1))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numPatientsJButton)
                            .addComponent(addJButton)
                            .addComponent(removeJButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(displayJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(700, 700, 700))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(symptomJLabel)
                            .addComponent(priorityJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJTextActionPerformed

    private void numPatientsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPatientsJButtonActionPerformed
        // TODO add your handling code here:
        jTextAreaDisplay.append("There are " + myPQueue.size() + " patients already in the queue"+ "\n");
    }//GEN-LAST:event_numPatientsJButtonActionPerformed

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        // TODO add your handling code here:
        String name, symptoms;
        int priority;
        Integer priorityINT;
        
        Customer p = new Customer();
        name = nameJText.getText();
        symptoms = symptomJText.getText();
        p.setName(name);
        p.setSymptom(symptoms);
        
        priorityINT = new Integer (priorityJText.getText());
        priority = priorityINT.intValue();
        myPQueue.enqueue(priority,p);

        jTextAreaDisplay.append(nameJText.getText() + " your details have been successfully added to the queue"+ "\n");
        nameJText.setText("");
        symptomJText.setText("");
        priorityJText.setText("");
    }//GEN-LAST:event_addJButtonActionPerformed

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJButtonActionPerformed
        // TODO add your handling code here:

        if(!myPQueue.isEmpty()){
            PQElement pqelem = (PQElement)myPQueue.dequeue();
            Customer p1 = (Customer)pqelem.getElement();
            
            jTextAreaDisplay.append("The doctor is now ready to see " + p1.getName());
            jTextAreaDisplay.append("  Symptoms: " + p1.getSymptom());
            jTextAreaDisplay.append("  Priority: " + pqelem.getKey()+ "\n");
        }
        else
            jTextAreaDisplay.append("There are no more patients waiting"+ "\n");
    }//GEN-LAST:event_removeJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void priorityJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priorityJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priorityJTextActionPerformed

    private void listJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listJButtonActionPerformed
        // TODO add your handling code here:
        jTextAreaDisplay.append("The patients waiting in the queue...."+ "\n");
        jTextAreaDisplay.append(myPQueue.printPQueue()+ "\n");
    }//GEN-LAST:event_listJButtonActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JLabel displayJLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDisplay;
    private javax.swing.JButton listJButton;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJText;
    private javax.swing.JButton numPatientsJButton;
    private javax.swing.JTextField priorityJText;
    private javax.swing.JButton removeJButton;
    private javax.swing.JLabel symptomJLabel;
    private javax.swing.JLabel symptomJLabel1;
    private javax.swing.JTextField symptomJText;
    private javax.swing.JLabel welcomeJLabel;
    // End of variables declaration//GEN-END:variables

}
